env:
    RCLONE_CONFIG: "ENCRYPTED[4895dafbeedcd240d24cbd2faaa83231cf4bd310a4b0d1f1c38ca2b37c4603c5cf1b6e84fd9194c2b7430c4486796387]"
    TG_TOKEN: "ENCRYPTED[50701e9f27f834a4a99c0aa06f8f1a1c85cc923f196a7554d8204ea55ec7289d82eebc11930d132fdf8a355d42f1fdbf]"
    TG_CHAT_ID: "ENCRYPTED[a4a78dd24020e099215701732a11b071378a3912e9c550ac3acd3dd64350c78ceea095d907dc840f21e77897b775dbe1]"
    FOLDER_CACHE_UPLOAD: ConquerOS
    MANIFEST: https://github.com/ConquerOS/manifest.git -b eleven
    DT: https://github.com/c3eru/device_trees -b 404
    VT: https://github.com/c3eru/vendor_tree -b 11.0
    KT: https://github.com/c3eru/kernel_xiaomi_citrus_sm6115 -b rvc
    TC: https://github.com/kdrag0n/proton-clang -b master prebuilts/clang/host/linux-x86/clang-proton

task:
  name: "Collecting cache..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       
       # =========================================
       - export DEBIAN_FRONTEND=noninteractive
       - export ALLOW_MISSING_DEPENDENCIES=true
       - export SELINUX_IGNORE_NEVERALLOW=true
       - export CC=clang
       - export CLANG_TRIPLE=aarch64-linux-gnu-
       - export CROSS_COMPILE=aarch64-linux-gnu-
       - export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
       # =========================================
       
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "c3eru"
       - git config --global user.email "yyprjkt@gmail.com"
       - mkdir -p /tmp/ccache
       - rclone copy mobx:$FOLDER_CACHE_UPLOAD/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - cd /tmp/rom
      
      # Manifest
      - repo init -q --no-repo-verify --depth=1 -u $MANIFEST -g default,-device,-mips,-darwin,-notdefault
      
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      
      # DT/VT/KT/TC
      - git clone --depth=1 $DT device/xiaomi/juice
      - git clone --depth=1 $VT vendor/xiaomi/juice
      - git clone --depth=1 $KT kernel/xiaomi/juice
      - git clone --depth=1 $TC

  Build_script:
      - ./collect.sh

  Upload_script:
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Collecting cache is complete!"
      - rclone copy ccache.tar.gz mobx:$FOLDER_CACHE_UPLOAD -P
 
