env:
    RCLONE_CONFIG: "ENCRYPTED[c0efdb804bdcc75ad2862f1d55873d0e7c2d70813588ac6c9c619854e87f5a3be93e41ccef73e108039d276fcda7a70f]"
    TG_TOKEN: "ENCRYPTED[50701e9f27f834a4a99c0aa06f8f1a1c85cc923f196a7554d8204ea55ec7289d82eebc11930d132fdf8a355d42f1fdbf]"
    TG_CHAT_ID: "ENCRYPTED[a4a78dd24020e099215701732a11b071378a3912e9c550ac3acd3dd64350c78ceea095d907dc840f21e77897b775dbe1]"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build baru terdeteksi!"
       
       #===========================================
       - export DEBIAN_FRONTEND=noninteractive
       - export ALLOW_MISSING_DEPENDENCIES=true
       - export SELINUX_IGNORE_NEVERALLOW=true
       - export CC=clang
       - export CLANG_TRIPLE=aarch64-linux-gnu-
       - export CROSS_COMPILE=aarch64-linux-gnu-
       - export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
       #===========================================

       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "c3eru"
       - git config --global user.email "yyprjkt@gmail.com"
       - mkdir -p /tmp/ccache
       - rclone copy mobx:RohieOS/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Menyinkronkan Sumber..."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai sinkronisasi Sumber..."
      
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/RohieOS/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/c3eru/device_trees -b ro device/xiaomi/juice
      - git clone --depth=1 https://github.com/c3eru/vendor_tree --single-branch -b 11.0 vendor/xiaomi/juice
      - git clone --depth=1 https://github.com/c3eru/kernel_xiaomi_citrus_sm6115 -b rvc kernel/xiaomi/juice
      - git clone --depth=1 https://github.com/kdrag0n/proton-clang -b master prebuilts/clang/host/linux-x86/clang-proton

      # Anu
#      - rm -rf vendor/aosp
#      - git clone --depth=1 https://github.com/c3eru/vendor_aosp -b eleven-plus vendor/aosp

      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sinkronisasi Selesai!"
      - echo "============================"
      - echo "Sinkronisasi Selesai!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      
      - ./collect.sh
#      - ./final.sh

      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls RohieOS*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Mengunggah Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading Build $(cd /tmp/rom/out/target/product/juice/ && ls RohieOS*.zip)"
      
#      - rclone copy /tmp/rom/out/target/product/juice/*.zip mobx:juice -P

      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls *.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Download link https://cloud.mobxs.workers.dev/juice/$(cd /tmp/rom/out/target/product/juice/ && ls RohieOS*.zip)"
      
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp

      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz mobx:RohieOS -P

      - echo " "
      - echo "============================"
      - echo "Build Berhasil Diunggah!"
      - echo "============================"
 
